### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ashtonmths** [PLASMAchicken/easy-djs-commandhandler#17]
How do I set the time for Cooldown in cooldown group?

**Comment by Subtilizer28** [comment]
@PLASMAchicken

**Comment by Subtilizer28** [comment]
@PLASMAchicken

**Comment by Subtilizer28** [comment]
@DeltaRade

**Comment by PLASMAchicken** [comment]
You set the cooldown and cooldown Group to the same thing in all commands of the group.

**Comment by ashtonmths** [comment]
So I have gotta do this first. 
`cooldownGroup: "name"`

After this i should do
`cooldown: "15s"`
In all files. Am I right??

**Comment by PLASMAchicken** [comment]
Yes

**Comment by ashtonmths** [comment]
Ohk. Thanks for the help!!!
